# -*- coding: utf-8 -*-
{
    "name": "Expediente Médico Salud y Hogar",
    "author": "IT Admin",
    "version": "13.0.0.1",
    "category": "Other",
    "depends": ['sale_stock','base','calendar'],
    "data": [
        'views/res_partner_view.xml',
        'data/sequence_data.xml',
        'security/ir.model.access.csv',
        'security/syh_module_security.xml',
        'report/report_expediente_clinico.xml',
        'report/report_circp_syh.xml',
        'report/report_coni_syh.xml',
        'report/report_coni_somnox.xml',
        'report/report_receta.xml',
        'report/report_solicitud.xml',
        'report/report_interconsulta.xml',
        'report/report_soliservicio.xml',
        'report/report_traslado.xml',
        'report/report_causamuerte.xml',
        'report/report_nota_defuncion.xml',
        'views/menu.xml',
        'views/expediente_clinico.xml',
        'views/pacientes.xml',
        'views/notas_de_evolucion.xml',
        'views/citas_salud.xml',
        'views/recetas.xml',
        'views/solicitud_estudio.xml',
        'views/consentimiento_informado.xml',
        'views/otros_documentos.xml',
        'views/interconsulta.xml',
        'data/catalogos.cie10.csv',	
        'views/formatos.xml',
        'views/email_template.xml',
        'data/heredo.familiar.csv',
        'data/infecto.contagiosas.csv',
        'data/cronico.degenerativas.csv',
        'data/estudios.diagnosticos.csv',
        'data/edad.csv',
        'data/tipo.alergias.csv',
        'views/traslado.xml',
        'views/causamuerte.xml',
        'views/nota_defuncion.xml',
        'views/hoja_enfermeria.xml',
    ],
    "license": 'AGPL-3',
    'installable': True,
    'images': [''],
}
